spring.application.name=gestionArchivo
server.port:8081

app.auth.username=admin
app.auth.password=admin123

security.jwt.secret=gestionArchivo-super-secret-key-change-me-2026
security.jwt.issuer=gestionArchivo
security.jwt.expiration-ms=3600000

spring.datasource.url=jdbc:postgresql://localhost:5432/tu_base_de_datos
spring.datasource.username=postgres
spring.datasource.password=25706123aS.

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect   
